
import type { Question } from './azure-data'; // Reusing the Question type

export interface Exam {
  id: string;
  name: string;
  description: string;
  questions: Question[]; // Target: 50 questions per exam
}

export const exams: Exam[] = [
  {
    id: 'cloud-concepts-exam',
    name: 'Cloud Concepts Exam',
    description: 'Test your understanding of fundamental cloud computing concepts. Covers topics like shared responsibility, cloud models (public, private, hybrid), consumption-based models, and cloud service types (IaaS, PaaS, SaaS). Target: 50 questions.',
    questions: [
      {
        id: 'cc-exam-q1',
        text: 'Which of the following best defines cloud computing?',
        options: [
          'Physical servers located in an on-premises data center',
          'A model for enabling convenient, on-demand network access to shared computing resources',
          'Software that runs only on local machines',
          'An isolated network used exclusively by one organization',
        ],
        correctAnswerIndex: 1,
        feedback: 'Cloud computing is defined as a model that enables convenient, on-demand access to shared pools of configurable computing resources over the internet.',
      },
      {
        id: 'cc-exam-q2',
        text: 'What is a key benefit of cloud computing related to resource allocation?',
        options: [
          'Paying for unused capacity',
          'Fixed infrastructure costs',
          'Scalability to meet changing business needs',
          'Manual provisioning of hardware',
        ],
        correctAnswerIndex: 2,
        feedback: 'One of the main benefits of cloud computing is scalability — the ability to scale up or down based on demand automatically or with minimal effort.',
      },
      {
        id: 'cc-exam-q3',
        text: 'Which responsibility does the customer typically have in the shared responsibility model?',
        options: [
          'Maintaining the physical security of the data centers',
          'Managing the operating system updates of virtual machines',
          'Ensuring the availability of the cloud platform',
          'Providing environmental controls for server racks',
        ],
        correctAnswerIndex: 1,
        feedback: 'In the shared responsibility model, the customer is responsible for managing guest operating systems, applications, and configurations.',
      },
      {
        id: 'cc-exam-q4',
        text: 'Which cloud deployment model is fully managed by a third-party provider and accessible over the internet?',
        options: ['Private cloud', 'Hybrid cloud', 'Public cloud', 'Community cloud'],
        correctAnswerIndex: 2,
        feedback: 'Public clouds are owned and operated by third-party providers like Microsoft Azure, Amazon AWS, or Google GCP, and are accessible over the internet.',
      },
      {
        id: 'cc-exam-q5',
        text: 'In which scenario would a private cloud be most appropriate?',
        options: [
          'When maximum scalability is needed',
          'When compliance requires data to remain on-premises',
          'When reducing operational overhead is a priority',
          'When sharing resources across organizations is required',
        ],
        correctAnswerIndex: 1,
        feedback: 'Private clouds are often used when organizations require more control over their data and infrastructure, such as for regulatory or compliance reasons.',
      },
      {
        id: 'cc-exam-q6',
        text: 'Which cloud model allows an organization to use both public and private clouds while maintaining the ability to move workloads between them?',
        options: ['Public cloud', 'Private cloud', 'Hybrid cloud', 'Community cloud'],
        correctAnswerIndex: 2,
        feedback: 'Hybrid cloud combines public and private clouds, allowing data and applications to be shared between them, offering flexibility and optimization.',
      },
      {
        id: 'cc-exam-q7',
        text: 'Which pricing model allows customers to pay only for the resources they consume?',
        options: ['Subscription-based model', 'Reserved instance model', 'Consumption-based model', 'Free-tier model'],
        correctAnswerIndex: 2,
        feedback: 'The consumption-based model charges users only for the resources they actually use, similar to utility billing (e.g., electricity).',
      },
      {
        id: 'cc-exam-q8',
        text: 'Which of the following best describes the consumption-based pricing model?',
        options: [
          'Pay upfront for a fixed amount of resources',
          'Pay a monthly fee regardless of usage',
          'Pay only for what you use',
          'Pay after a free trial period ends',
        ],
        correctAnswerIndex: 2,
        feedback: 'The consumption-based model allows cost-effective scaling by charging based on actual usage rather than pre-purchased capacity.',
      },
      {
        id: 'cc-exam-q9',
        text: 'Which cloud pricing model involves paying a fixed monthly fee for a set of services?',
        options: ['Pay-as-you-go', 'Free tier', 'Reserved instances', 'Subscription-based'],
        correctAnswerIndex: 3,
        feedback: 'Some cloud services offer subscription-based pricing where users pay a recurring fee for access to a suite of features.',
      },
      {
        id: 'cc-exam-q10',
        text: 'Which term refers to a service that automatically provisions and manages application runtime without requiring infrastructure management?',
        options: [
          'Infrastructure as a Service (IaaS)',
          'Platform as a Service (PaaS)',
          'Serverless computing',
          'Software as a Service (SaaS)',
        ],
        correctAnswerIndex: 2,
        feedback: 'Serverless computing abstracts infrastructure management, allowing developers to focus solely on writing code.',
      },
      {
        id: 'cc-exam-q11',
        text: 'Which of the following is a benefit of high availability in the cloud?',
        options: [
          'Reduced storage costs',
          'Elimination of user access issues',
          'Continuous operation despite failures',
          'Faster software development cycles',
        ],
        correctAnswerIndex: 2,
        feedback: 'High availability ensures that applications and services remain accessible even during outages or maintenance.',
      },
      {
        id: 'cc-exam-q12',
        text: 'Which cloud benefit ensures that applications can handle increased traffic by adding more resources?',
        options: ['Security', 'Reliability', 'Scalability', 'Predictability'],
        correctAnswerIndex: 2,
        feedback: 'Scalability allows cloud applications to grow and adapt to changes in demand by dynamically allocating more compute, storage, or bandwidth.',
      },
      {
        id: 'cc-exam-q13',
        text: 'Which benefit of cloud computing ensures consistent performance and uptime?',
        options: ['Scalability', 'Manageability', 'Reliability', 'Elasticity'],
        correctAnswerIndex: 2,
        feedback: 'Reliability means the system performs consistently under stated conditions, ensuring predictable behavior and uptime.',
      },
      {
        id: 'cc-exam-q14',
        text: 'Which of the following is a benefit of using cloud services for governance and compliance?',
        options: [
          'Increased hardware costs',
          'Centralized control and visibility',
          'Limited access to audit logs',
          'Manual configuration of security policies',
        ],
        correctAnswerIndex: 1,
        feedback: 'Cloud platforms provide centralized tools for monitoring, auditing, and enforcing governance policies across resources.',
      },
      {
        id: 'cc-exam-q15',
        text: 'Which cloud feature helps ensure that applications continue running even if part of the infrastructure fails?',
        options: ['Auto-scaling', 'Load balancing', 'High availability', 'Data replication'],
        correctAnswerIndex: 2,
        feedback: 'High availability is achieved through redundancy and fault tolerance mechanisms to minimize downtime.',
      },
      {
        id: 'cc-exam-q16',
        text: 'Which cloud computing benefit allows businesses to reduce capital expenditures?',
        options: ['Scalability', 'Elasticity', 'OpEx vs CapEx shift', 'Multi-tenancy'],
        correctAnswerIndex: 2,
        feedback: 'Cloud computing shifts IT spending from capital expenses (CapEx) to operational expenses (OpEx), reducing the need for large upfront investments.',
      },
      {
        id: 'cc-exam-q17',
        text: 'Which of the following best describes elasticity in cloud computing?',
        options: [
          'Ability to scale resources manually',
          'Ability to scale resources automatically based on demand',
          'Ability to store unlimited data',
          'Ability to run applications on physical servers',
        ],
        correctAnswerIndex: 1,
        feedback: 'Elasticity refers to the automatic scaling of resources up or down based on workload demands.',
      },
      {
        id: 'cc-exam-q18',
        text: 'Which of the following is a benefit of manageability in the cloud?',
        options: [
          'More complex patching processes',
          'Need for manual backups',
          'Simplified resource management via portals and APIs',
          'Requirement for on-site technicians',
        ],
        correctAnswerIndex: 2,
        feedback: 'Cloud platforms offer simplified management through dashboards, automation, and APIs, reducing administrative overhead.',
      },
      {
        id: 'cc-exam-q19',
        text: 'Which of the following is NOT a core characteristic of cloud computing?',
        options: ['Measured service', 'Resource pooling', 'Dedicated hardware per tenant', 'Broad network access'],
        correctAnswerIndex: 2,
        feedback: 'Cloud computing relies on multi-tenant architectures where resources are pooled and shared among users, not dedicated per tenant.',
      },
      {
        id: 'cc-exam-q20',
        text: 'Which of the following best describes "multi-tenancy" in cloud computing?',
        options: [
          'Multiple users share the same physical infrastructure',
          'Each customer has a dedicated server',
          'Users cannot interact with each other',
          'All tenants must use the same operating system',
        ],
        correctAnswerIndex: 0,
        feedback: 'Multi-tenancy allows multiple customers (tenants) to share the same cloud infrastructure while maintaining isolation at the software level.',
      },
      {
        id: 'cc-exam-q21',
        text: 'Which of the following is a common use case for a hybrid cloud model?',
        options: [
          'Storing sensitive data offsite permanently',
          'Running non-sensitive applications in the public cloud and keeping critical data in a private cloud',
          'Migrating all workloads to a single public cloud provider',
          'Isolating test environments from production',
        ],
        correctAnswerIndex: 1,
        feedback: 'Hybrid cloud is ideal for organizations that want to leverage public cloud benefits while retaining control over sensitive data in private environments.',
      },
      {
        id: 'cc-exam-q22',
        text: 'Which of the following cloud models provides the highest level of control over infrastructure?',
        options: ['SaaS', 'PaaS', 'IaaS', 'Serverless'],
        correctAnswerIndex: 2,
        feedback: 'IaaS gives users the most control over virtual machines, networks, and storage compared to higher-level services like PaaS or SaaS.',
      },
      {
        id: 'cc-exam-q23',
        text: 'Which of the following is a primary benefit of using the cloud for disaster recovery?',
        options: ['Higher latency', 'Reduced data redundancy', 'Rapid recovery and failover capabilities', 'Increased dependency on local hardware'],
        correctAnswerIndex: 2,
        feedback: 'Cloud-based disaster recovery offers fast recovery times, automated failover, and geographic redundancy.',
      },
      {
        id: 'cc-exam-q24',
        text: 'Which cloud computing model is best suited for organizations that want to run custom applications without managing the underlying infrastructure?',
        options: ['IaaS', 'PaaS', 'SaaS', 'Serverless'],
        correctAnswerIndex: 1,
        feedback: 'PaaS provides a development and deployment environment without requiring management of the underlying infrastructure.',
      },
      {
        id: 'cc-exam-q25',
        text: 'Which of the following best describes "scalability" in cloud computing?',
        options: [
          'Ability to increase or decrease resources based on demand',
          'Ability to encrypt data automatically',
          'Ability to store data in multiple formats',
          'Ability to host multiple applications on a single server',
        ],
        correctAnswerIndex: 0,
        feedback: 'Scalability allows cloud resources to expand or contract depending on workload requirements.',
      },
      {
        id: 'cc-exam-q26',
        text: 'Which of the following best describes "elasticity" in cloud computing?',
        options: [
          'Ability to change the price of cloud services dynamically',
          'Ability to add or remove resources automatically based on demand',
          'Ability to run applications offline',
          'Ability to deploy applications in multiple regions',
        ],
        correctAnswerIndex: 1,
        feedback: 'Elasticity refers to the automatic adjustment of resources in response to workload changes.',
      },
      {
        id: 'cc-exam-q27',
        text: 'Which of the following is a benefit of using cloud services for security?',
        options: [
          'Complete removal of threats',
          'Reduced visibility into security events',
          'Centralized security management and threat detection',
          'Increased complexity in managing firewalls',
        ],
        correctAnswerIndex: 2,
        feedback: 'Cloud providers offer advanced security tools and centralized dashboards to monitor and respond to threats effectively.',
      },
      {
        id: 'cc-exam-q28',
        text: 'Which of the following is a benefit of reliability in the cloud?',
        options: [
          'Lower costs due to reduced resource usage',
          'Consistent performance and uptime',
          'Greater flexibility in choosing hardware',
          'Faster deployment of new applications',
        ],
        correctAnswerIndex: 1,
        feedback: 'Reliability ensures that systems perform consistently and meet expected service levels.',
      },
      {
        id: 'cc-exam-q29',
        text: 'Which of the following best describes the "defense-in-depth" security strategy?',
        options: [
          'Using a single strong firewall to protect all assets',
          'Implementing multiple layers of security controls',
          'Relying solely on encryption for data protection',
          'Minimizing the number of security tools used',
        ],
        correctAnswerIndex: 1,
        feedback: 'Defense-in-depth involves layering multiple security measures (firewalls, encryption, IAM, etc.) to protect systems comprehensively.',
      },
      {
        id: 'cc-exam-q30',
        text: 'Which of the following is a benefit of using cloud services for governance?',
        options: [
          'Increased risk of unauthorized access',
          'Simplified compliance and policy enforcement',
          'Decreased visibility into resource usage',
          'Complex configuration of cloud environments',
        ],
        correctAnswerIndex: 1,
        feedback: 'Cloud platforms provide built-in governance tools like tagging, policies, and role-based access control (RBAC) to simplify compliance and management.',
      },
      // You will need to add 20 more questions here to reach the 50 question target for this exam.
    ],
  },
  {
    id: 'azure-architecture-services-exam',
    name: 'Azure Architecture and Services Exam',
    description: 'Assess your knowledge of Azure\'s core architectural components, compute, networking, and storage services. Target: 50 questions.',
    questions: [
      {
        id: 'aas-exam-q31',
        text: 'Which cloud service model gives you full control over the operating system and applications?',
        options: ['SaaS', 'PaaS', 'IaaS', 'Serverless'],
        correctAnswerIndex: 2,
        feedback: 'Infrastructure as a Service (IaaS) allows customers to manage operating systems, applications, and configurations while the cloud provider manages the underlying infrastructure.',
      },
      {
        id: 'aas-exam-q32',
        text: 'Which of the following is an example of Software as a Service (SaaS)?',
        options: ['Azure Virtual Machines', 'Azure App Services', 'Microsoft 365 (e.g., Word Online)', 'Azure Kubernetes Service'],
        correctAnswerIndex: 2,
        feedback: 'SaaS delivers fully functional software applications over the internet, such as Microsoft 365, where users don\'t manage the infrastructure or platform.',
      },
      {
        id: 'aas-exam-q33',
        text: 'In which cloud service model does the cloud provider manage the infrastructure and platform, allowing developers to deploy applications without managing the underlying environment?',
        options: ['IaaS', 'PaaS', 'SaaS', 'Serverless'],
        correctAnswerIndex: 1,
        feedback: 'Platform as a Service (PaaS) abstracts infrastructure management and provides a platform for developing, running, and managing applications.',
      },
      {
        id: 'aas-exam-q34',
        text: 'Which cloud service type is best suited for deploying custom applications without managing virtual machines or networks?',
        options: ['IaaS', 'PaaS', 'SaaS', 'On-premises'],
        correctAnswerIndex: 1,
        feedback: 'PaaS services like Azure App Service allow developers to deploy and manage applications without worrying about the underlying infrastructure.',
      },
      {
        id: 'aas-exam-q35',
        text: 'Which of the following best describes a use case for IaaS?',
        options: [
          'Hosting a website using a managed web app service',
          'Running a virtual machine to test software in a controlled environment',
          'Using a cloud-based email service',
          'Developing a mobile app backend using a serverless function',
        ],
        correctAnswerIndex: 1,
        feedback: 'IaaS is ideal when you need full control over your environment, such as testing, development, or hosting workloads on virtual machines.',
      },
      {
        id: 'aas-exam-q36',
        text: 'Which cloud service model offers the least amount of administrative overhead for the customer?',
        options: ['IaaS', 'PaaS', 'SaaS', 'Hybrid'],
        correctAnswerIndex: 2,
        feedback: 'In SaaS, the cloud provider manages everything — infrastructure, platform, and application — leaving users to focus only on usage.',
      },
      {
        id: 'aas-exam-q37',
        text: 'Which cloud service model would be most appropriate for a business that wants to run enterprise resource planning (ERP) software without managing servers?',
        options: ['IaaS', 'PaaS', 'SaaS', 'Private cloud'],
        correctAnswerIndex: 2,
        feedback: 'SaaS ERP solutions like Dynamics 365 Business Central are hosted and maintained by the provider, reducing operational complexity.',
      },
      {
        id: 'aas-exam-q38',
        text: 'Which cloud service type allows developers to deploy code without provisioning or managing servers?',
        options: ['IaaS', 'PaaS', 'SaaS', 'Serverless'],
        correctAnswerIndex: 3,
        feedback: 'Serverless computing allows developers to upload and run code without managing the underlying infrastructure or runtime environment.',
      },
      {
        id: 'aas-exam-q39',
        text: 'Which of the following best describes a use case for serverless computing?',
        options: [
          'Running a large relational database',
          'Deploying a long-running background service',
          'Executing event-driven functions triggered by HTTP requests',
          'Managing a cluster of virtual machines',
        ],
        correctAnswerIndex: 2,
        feedback: 'Serverless functions are ideal for short-lived, event-driven tasks such as processing form submissions, image resizing, or triggering workflows.',
      },
      {
        id: 'aas-exam-q40',
        text: 'Which cloud service type is best for organizations that want to migrate existing applications with minimal changes?',
        options: ['IaaS', 'PaaS', 'SaaS', 'Serverless'],
        correctAnswerIndex: 0,
        feedback: 'IaaS supports lift-and-shift migrations, where applications are moved to the cloud with little to no modification.',
      },
      {
        id: 'aas-exam-q41',
        text: 'Which cloud service model allows users to configure middleware components such as databases and application servers?',
        options: ['IaaS', 'PaaS', 'SaaS', 'Serverless'],
        correctAnswerIndex: 0,
        feedback: 'With IaaS, users have full access to the operating system and can install and configure middleware components themselves.',
      },
      {
        id: 'aas-exam-q42',
        text: 'Which cloud service type is best for a company that wants to develop and host a web application quickly without managing infrastructure?',
        options: ['IaaS', 'PaaS', 'SaaS', 'On-premises'],
        correctAnswerIndex: 1,
        feedback: 'PaaS platforms like Azure Web Apps allow developers to deploy and scale applications without worrying about VMs, storage, or networking.',
      },
      {
        id: 'aas-exam-q43',
        text: 'Which cloud service model includes automatic scaling and patching of the operating system?',
        options: ['IaaS', 'PaaS', 'SaaS', 'Bare metal'],
        correctAnswerIndex: 1,
        feedback: 'In PaaS, the cloud provider manages the underlying OS, including updates and scaling, so developers can focus on their apps.',
      },
      {
        id: 'aas-exam-q44',
        text: 'Which of the following is a benefit of using SaaS?',
        options: [
          'Full control over application configuration',
          'Reduced maintenance and support costs',
          'Customizable infrastructure',
          'Ability to install third-party software',
        ],
        correctAnswerIndex: 1,
        feedback: 'SaaS reduces the burden of software maintenance and support since the provider handles all aspects of the application lifecycle.',
      },
      {
        id: 'aas-exam-q45',
        text: 'Which cloud service model is best suited for businesses that want to use productivity tools like email, collaboration, and file sharing without managing the software or hardware?',
        options: ['IaaS', 'PaaS', 'SaaS', 'Serverless'],
        correctAnswerIndex: 2,
        feedback: 'SaaS provides ready-to-use applications delivered over the internet, such as Microsoft Teams, Outlook.com, or Google Workspace.',
      },
      {
        id: 'aas-exam-q46',
        text: 'Which cloud service model typically requires the least amount of manual configuration by the user?',
        options: ['IaaS', 'PaaS', 'SaaS', 'Hybrid cloud'],
        correctAnswerIndex: 2,
        feedback: 'SaaS applications are pre-configured and ready to use, requiring minimal setup from the end-user.',
      },
      {
        id: 'aas-exam-q47',
        text: 'Which of the following is a primary difference between PaaS and SaaS?',
        options: [
          'PaaS is used for infrastructure, SaaS is used for networking',
          'PaaS allows customization of applications, SaaS does not',
          'PaaS requires managing the OS, SaaS does not',
          'PaaS is free, SaaS requires a subscription',
        ],
        correctAnswerIndex: 1,
        feedback: 'PaaS enables developers to build and customize applications, whereas SaaS provides fixed-functionality applications managed entirely by the provider.',
      },
      {
        id: 'aas-exam-q48',
        text: 'Which cloud service model is best described as "code + execution environment"?',
        options: ['IaaS', 'PaaS', 'SaaS', 'Serverless'],
        correctAnswerIndex: 3,
        feedback: 'Serverless computing allows developers to write and deploy code that runs in response to events, with the platform handling execution automatically.',
      },
      {
        id: 'aas-exam-q49',
        text: 'Which cloud service model is most suitable for DevOps teams building continuous integration/continuous deployment (CI/CD) pipelines?',
        options: ['IaaS', 'PaaS', 'SaaS', 'Serverless'],
        correctAnswerIndex: 1,
        feedback: 'PaaS offers integrated tools and environments that streamline CI/CD workflows, making it easier for DevOps teams to automate deployments.',
      },
      {
        id: 'aas-exam-q50',
        text: 'Which of the following is a disadvantage of using SaaS compared to PaaS or IaaS?',
        options: [
          'High upfront cost',
          'Limited ability to customize applications',
          'Requires managing infrastructure',
          'Increased latency',
        ],
        correctAnswerIndex: 1,
        feedback: 'SaaS applications are generally not customizable beyond basic settings, limiting flexibility compared to PaaS or IaaS models.',
      },
      // You will need to add 30 more questions here to reach the 50 question target for this exam.
    ],
  },
  {
    id: 'azure-identity-access-security-exam',
    name: 'Azure Identity, Access, and Security Exam',
    description: 'Challenge your knowledge on directory services, authentication, external identities, access control, and security models in Azure. Target: 50 questions.',
    questions: [
      {
        id: 'aias-exam-q1',
        text: 'What is the primary function of Microsoft Entra ID?',
        options: [
          'To manage virtual machines',
          'To provide identity and access management',
          'To store application data',
          'To monitor network traffic',
        ],
        correctAnswerIndex: 1,
        feedback: 'Microsoft Entra ID is Azure\'s cloud-based identity and access management service.',
      },
      {
        id: 'aias-exam-q2',
        text: 'Which authentication method enhances security by requiring more than one form of verification?',
        options: ['Single Sign-On (SSO)', 'Passwordless authentication', 'Multi-Factor Authentication (MFA)', 'Basic authentication'],
        correctAnswerIndex: 2,
        feedback: 'Multi-Factor Authentication (MFA) adds a layer of security by requiring users to provide two or more verification factors.',
      },
      {
        id: 'aias-exam-q3',
        text: 'What does Azure RBAC stand for?',
        options: ['Resource Based Access Control', 'Role Based Access Control', 'Rule Based Access Control', 'Region Based Access Control'],
        correctAnswerIndex: 1,
        feedback: 'RBAC stands for Role-Based Access Control, used for managing access to Azure resources.',
      },
      {
        id: 'aias-exam-q4',
        text: 'Microsoft Defender for Cloud primarily helps with what?',
        options: ['Cost optimization', 'Cloud security posture management and workload protection', 'Data migration', 'Application development'],
        correctAnswerIndex: 1,
        feedback: 'Microsoft Defender for Cloud is a tool for security posture management and threat protection for cloud workloads.',
      },
      {
        id: 'aias-exam-q5',
        text: 'What type of external identity solution is Azure AD B2C designed for?',
        options: ['Business-to-Business collaboration', 'Business-to-Customer identity management', 'Internal employee access', 'Server-to-server authentication'],
        correctAnswerIndex: 1,
        feedback: 'Azure AD B2C is designed for managing customer identities for consumer-facing applications.',
      },
      {
        id: 'aias-exam-q6',
        text: 'Conditional Access policies in Microsoft Entra ID are evaluated based on signals such as:',
        options: ['User location, device compliance, application', 'VM size, storage account type, network bandwidth', 'Database performance, CPU utilization, memory usage', 'Subscription type, resource group name, tags'],
        correctAnswerIndex: 0,
        feedback: 'Conditional Access policies use signals like user, location, device, application, and real-time risk to enforce organizational policies.',
      },
      {
        id: 'aias-exam-q7',
        text: 'What is the core principle of the Zero Trust security model?',
        options: ['Trust all internal network traffic', 'Verify everything explicitly, assume breach', 'Grant broad permissions by default', 'Focus security only on the perimeter'],
        correctAnswerIndex: 1,
        feedback: 'The Zero Trust model operates on the principle of "never trust, always verify" and assumes that a breach is inevitable or has already occurred.',
      },
      {
        id: 'aias-exam-q8',
        text: 'Microsoft Entra Domain Services provides:',
        options: ['A NoSQL database service', 'Managed domain services like domain join for Azure VMs', 'A content delivery network', 'A firewall service'],
        correctAnswerIndex: 1,
        feedback: 'Microsoft Entra Domain Services offers managed domain services such as domain join, Group Policy, LDAP, and Kerberos/NTLM authentication, compatible with traditional Active Directory.',
      },
      {
        id: 'aias-exam-q9',
        text: 'An example of a passwordless authentication method is:',
        options: ['Using a very complex password', 'Using the Microsoft Authenticator app for phone sign-in', 'Changing passwords frequently', 'Storing passwords in a browser'],
        correctAnswerIndex: 1,
        feedback: 'Passwordless methods like phone sign-in with Microsoft Authenticator, FIDO2 security keys, or Windows Hello for Business eliminate the need for traditional passwords.',
      },
      {
        id: 'aias-exam-q10',
        text: 'The defense-in-depth security strategy relies on:',
        options: ['A single, robust security tool', 'Encrypting all data by default', 'Multiple layers of security controls', 'User training as the primary defense'],
        correctAnswerIndex: 2,
        feedback: 'Defense-in-depth employs multiple, layered security controls so that if one layer is bypassed, others are in place to protect assets.',
      },
      // You will need to add 40 more questions here to reach the 50 question target for this exam.
    ],
  },
  {
    id: 'azure-management-governance-exam',
    name: 'Azure Management and Governance Exam',
    description: 'Test your skills in cost management, governance tools (Policy, Purview), resource deployment, and monitoring in Azure. Target: 50 questions.',
    questions: [
      {
        id: 'amg-exam-q1',
        text: 'Which Azure tool helps estimate the ongoing costs of Azure services you plan to deploy?',
        options: ['TCO Calculator', 'Azure Advisor', 'Azure Pricing Calculator', 'Azure Cost Management'],
        correctAnswerIndex: 2,
        feedback: 'The Azure Pricing Calculator is used to estimate the costs of specific Azure services for new or planned deployments.',
      },
      {
        id: 'amg-exam-q2',
        text: 'What is the primary benefit of using Azure Policy?',
        options: [
          'To automate backups',
          'To enforce organizational standards and compliance',
          'To monitor application performance',
          'To manage DNS records',
        ],
        correctAnswerIndex: 1,
        feedback: 'Azure Policy helps you create, assign, and manage policies to enforce rules and ensure your Azure resources stay compliant with corporate standards and SLAs.',
      },
      {
        id: 'amg-exam-q3',
        text: 'A ReadOnly resource lock in Azure prevents what?',
        options: ['Only deletion of the resource', 'Only modification of the resource', 'Both deletion and modification of the resource', 'Only access to the resource'],
        correctAnswerIndex: 2,
        feedback: 'A ReadOnly lock prevents users from deleting or updating a resource. They can only read it.',
      },
      {
        id: 'amg-exam-q4',
        text: 'Azure Arc is designed to:',
        options: ['Manage Azure-native resources only', 'Extend Azure management to on-premises, edge, and multicloud environments', 'Provide a virtual desktop experience', 'Archive old data automatically'],
        correctAnswerIndex: 1,
        feedback: 'Azure Arc allows you to manage resources located outside of Azure (on-premises, other clouds, edge) using Azure management tools.',
      },
      {
        id: 'amg-exam-q5',
        text: 'Infrastructure as Code (IaC) primarily helps with:',
        options: ['Manual configuration of servers', 'Improving network latency', 'Automating and standardizing infrastructure deployment', 'Real-time threat detection'],
        correctAnswerIndex: 2,
        feedback: 'IaC enables managing and provisioning infrastructure through code, leading to automation, consistency, and repeatability.',
      },
      {
        id: 'amg-exam-q6',
        text: 'Azure Advisor provides recommendations for which of the following categories?',
        options: ['Cost, Security, Reliability, Performance, Operational Excellence', 'Networking, Storage, Compute, Databases, AI/ML', 'Development, Testing, Deployment, Monitoring, Support', 'Sales, Marketing, HR, Finance, Legal'],
        correctAnswerIndex: 0,
        feedback: 'Azure Advisor offers recommendations across five pillars: Cost, Security, Reliability, Performance, and Operational Excellence.',
      },
      {
        id: 'amg-exam-q7',
        text: 'If you need to be informed about Azure platform issues (like outages or planned maintenance) affecting your resources, which service should you use?',
        options: ['Azure Monitor', 'Azure Advisor', 'Azure Service Health', 'Azure Cost Management'],
        correctAnswerIndex: 2,
        feedback: 'Azure Service Health provides personalized alerts and guidance when Azure service issues or planned maintenance affect your resources.',
      },
      {
        id: 'amg-exam-q8',
        text: 'What is Microsoft Purview primarily used for?',
        options: ['Managing virtual machine backups', 'Unified data governance across an organization\'s data estate', 'Deploying applications to Kubernetes', 'Monitoring user sign-in activity'],
        correctAnswerIndex: 1,
        feedback: 'Microsoft Purview is a unified data governance service that helps you manage and govern your data across on-premises, multicloud, and SaaS environments.',
      },
      {
        id: 'amg-exam-q9',
        text: 'Which Azure tool provides a browser-accessible shell with Azure CLI and Azure PowerShell pre-installed?',
        options: ['Azure portal', 'Azure Resource Explorer', 'Azure Mobile App', 'Azure Cloud Shell'],
        correctAnswerIndex: 3,
        feedback: 'Azure Cloud Shell is an interactive, authenticated, browser-accessible shell for managing Azure resources, offering both Bash (with CLI) and PowerShell environments.',
      },
      {
        id: 'amg-exam-q10',
        text: 'Tags in Azure are primarily used for:',
        options: ['Increasing resource performance', 'Resource organization, cost management, and automation', 'Encrypting data at rest', 'Ensuring high availability'],
        correctAnswerIndex: 1,
        feedback: 'Tags are key-value pairs applied to Azure resources for organization, cost tracking, automation, and operational management.',
      },
      // You will need to add 40 more questions here to reach the 50 question target for this exam.
    ],
  },
];

export const getExamById = (id: string): Exam | undefined => {
  return exams.find((exam) => exam.id === id);
};

    