
import type { Question } from './azure-data'; // Reusing the Question type

export interface Exam {
  id: string;
  name: string;
  description: string;
  questions: Question[]; // Target: 50 questions per exam
}

export const exams: Exam[] = [
  {
    id: 'cloud-concepts-exam',
    name: 'Cloud Concepts Exam',
    description: 'Test your understanding of fundamental cloud computing concepts. Covers topics like shared responsibility, cloud models (public, private, hybrid), consumption-based models, and cloud service types (IaaS, PaaS, SaaS). Contains 30 questions. Target: 50 questions.',
    questions: [
      {
        id: 'cc-exam-q1',
        text: 'Which of the following best defines cloud computing?',
        options: [
          'Physical servers located in an on-premises data center',
          'A model for enabling convenient, on-demand network access to shared computing resources',
          'Software that runs only on local machines',
          'An isolated network used exclusively by one organization',
        ],
        correctAnswerIndex: 1,
        feedback: 'Cloud computing is defined as a model that enables convenient, on-demand access to shared pools of configurable computing resources over the internet.',
      },
      {
        id: 'cc-exam-q2',
        text: 'What is a key benefit of cloud computing related to resource allocation?',
        options: [
          'Paying for unused capacity',
          'Fixed infrastructure costs',
          'Scalability to meet changing business needs',
          'Manual provisioning of hardware',
        ],
        correctAnswerIndex: 2,
        feedback: 'One of the main benefits of cloud computing is scalability — the ability to scale up or down based on demand automatically or with minimal effort.',
      },
      {
        id: 'cc-exam-q3',
        text: 'Which responsibility does the customer typically have in the shared responsibility model?',
        options: [
          'Maintaining the physical security of the data centers',
          'Managing the operating system updates of virtual machines',
          'Ensuring the availability of the cloud platform',
          'Providing environmental controls for server racks',
        ],
        correctAnswerIndex: 1,
        feedback: 'In the shared responsibility model, the customer is responsible for managing guest operating systems, applications, and configurations.',
      },
      {
        id: 'cc-exam-q4',
        text: 'Which cloud deployment model is fully managed by a third-party provider and accessible over the internet?',
        options: ['Private cloud', 'Hybrid cloud', 'Public cloud', 'Community cloud'],
        correctAnswerIndex: 2,
        feedback: 'Public clouds are owned and operated by third-party providers like Microsoft Azure, Amazon AWS, or Google GCP, and are accessible over the internet.',
      },
      {
        id: 'cc-exam-q5',
        text: 'In which scenario would a private cloud be most appropriate?',
        options: [
          'When maximum scalability is needed',
          'When compliance requires data to remain on-premises',
          'When reducing operational overhead is a priority',
          'When sharing resources across organizations is required',
        ],
        correctAnswerIndex: 1,
        feedback: 'Private clouds are often used when organizations require more control over their data and infrastructure, such as for regulatory or compliance reasons.',
      },
      {
        id: 'cc-exam-q6',
        text: 'Which cloud model allows an organization to use both public and private clouds while maintaining the ability to move workloads between them?',
        options: ['Public cloud', 'Private cloud', 'Hybrid cloud', 'Community cloud'],
        correctAnswerIndex: 2,
        feedback: 'Hybrid cloud combines public and private clouds, allowing data and applications to be shared between them, offering flexibility and optimization.',
      },
      {
        id: 'cc-exam-q7',
        text: 'Which pricing model allows customers to pay only for the resources they consume?',
        options: ['Subscription-based model', 'Reserved instance model', 'Consumption-based model', 'Free-tier model'],
        correctAnswerIndex: 2,
        feedback: 'The consumption-based model charges users only for the resources they actually use, similar to utility billing (e.g., electricity).',
      },
      {
        id: 'cc-exam-q8',
        text: 'Which of the following best describes the consumption-based pricing model?',
        options: [
          'Pay upfront for a fixed amount of resources',
          'Pay a monthly fee regardless of usage',
          'Pay only for what you use',
          'Pay after a free trial period ends',
        ],
        correctAnswerIndex: 2,
        feedback: 'The consumption-based model allows cost-effective scaling by charging based on actual usage rather than pre-purchased capacity.',
      },
      {
        id: 'cc-exam-q9',
        text: 'Which cloud pricing model involves paying a fixed monthly fee for a set of services?',
        options: ['Pay-as-you-go', 'Free tier', 'Reserved instances', 'Subscription-based'],
        correctAnswerIndex: 3,
        feedback: 'Some cloud services offer subscription-based pricing where users pay a recurring fee for access to a suite of features.',
      },
      {
        id: 'cc-exam-q10',
        text: 'Which term refers to a service that automatically provisions and manages application runtime without requiring infrastructure management?',
        options: [
          'Infrastructure as a Service (IaaS)',
          'Platform as a Service (PaaS)',
          'Serverless computing',
          'Software as a Service (SaaS)',
        ],
        correctAnswerIndex: 2,
        feedback: 'Serverless computing abstracts infrastructure management, allowing developers to focus solely on writing code.',
      },
      {
        id: 'cc-exam-q11',
        text: 'Which of the following is a benefit of high availability in the cloud?',
        options: [
          'Reduced storage costs',
          'Elimination of user access issues',
          'Continuous operation despite failures',
          'Faster software development cycles',
        ],
        correctAnswerIndex: 2,
        feedback: 'High availability ensures that applications and services remain accessible even during outages or maintenance.',
      },
      {
        id: 'cc-exam-q12',
        text: 'Which cloud benefit ensures that applications can handle increased traffic by adding more resources?',
        options: ['Security', 'Reliability', 'Scalability', 'Predictability'],
        correctAnswerIndex: 2,
        feedback: 'Scalability allows cloud applications to grow and adapt to changes in demand by dynamically allocating more compute, storage, or bandwidth.',
      },
      {
        id: 'cc-exam-q13',
        text: 'Which benefit of cloud computing ensures consistent performance and uptime?',
        options: ['Scalability', 'Manageability', 'Reliability', 'Elasticity'],
        correctAnswerIndex: 2,
        feedback: 'Reliability means the system performs consistently under stated conditions, ensuring predictable behavior and uptime.',
      },
      {
        id: 'cc-exam-q14',
        text: 'Which of the following is a benefit of using cloud services for governance and compliance?',
        options: [
          'Increased hardware costs',
          'Centralized control and visibility',
          'Limited access to audit logs',
          'Manual configuration of security policies',
        ],
        correctAnswerIndex: 1,
        feedback: 'Cloud platforms provide centralized tools for monitoring, auditing, and enforcing governance policies across resources.',
      },
      {
        id: 'cc-exam-q15',
        text: 'Which cloud feature helps ensure that applications continue running even if part of the infrastructure fails?',
        options: ['Auto-scaling', 'Load balancing', 'High availability', 'Data replication'],
        correctAnswerIndex: 2,
        feedback: 'High availability is achieved through redundancy and fault tolerance mechanisms to minimize downtime.',
      },
      {
        id: 'cc-exam-q16',
        text: 'Which cloud computing benefit allows businesses to reduce capital expenditures?',
        options: ['Scalability', 'Elasticity', 'OpEx vs CapEx shift', 'Multi-tenancy'],
        correctAnswerIndex: 2,
        feedback: 'Cloud computing shifts IT spending from capital expenses (CapEx) to operational expenses (OpEx), reducing the need for large upfront investments.',
      },
      {
        id: 'cc-exam-q17',
        text: 'Which of the following best describes elasticity in cloud computing?',
        options: [
          'Ability to scale resources manually',
          'Ability to scale resources automatically based on demand',
          'Ability to store unlimited data',
          'Ability to run applications on physical servers',
        ],
        correctAnswerIndex: 1,
        feedback: 'Elasticity refers to the automatic scaling of resources up or down based on workload demands.',
      },
      {
        id: 'cc-exam-q18',
        text: 'Which of the following is a benefit of manageability in the cloud?',
        options: [
          'More complex patching processes',
          'Need for manual backups',
          'Simplified resource management via portals and APIs',
          'Requirement for on-site technicians',
        ],
        correctAnswerIndex: 2,
        feedback: 'Cloud platforms offer simplified management through dashboards, automation, and APIs, reducing administrative overhead.',
      },
      {
        id: 'cc-exam-q19',
        text: 'Which of the following is NOT a core characteristic of cloud computing?',
        options: ['Measured service', 'Resource pooling', 'Dedicated hardware per tenant', 'Broad network access'],
        correctAnswerIndex: 2,
        feedback: 'Cloud computing relies on multi-tenant architectures where resources are pooled and shared among users, not dedicated per tenant.',
      },
      {
        id: 'cc-exam-q20',
        text: 'Which of the following best describes "multi-tenancy" in cloud computing?',
        options: [
          'Multiple users share the same physical infrastructure',
          'Each customer has a dedicated server',
          'Users cannot interact with each other',
          'All tenants must use the same operating system',
        ],
        correctAnswerIndex: 0,
        feedback: 'Multi-tenancy allows multiple customers (tenants) to share the same cloud infrastructure while maintaining isolation at the software level.',
      },
      {
        id: 'cc-exam-q21',
        text: 'Which of the following is a common use case for a hybrid cloud model?',
        options: [
          'Storing sensitive data offsite permanently',
          'Running non-sensitive applications in the public cloud and keeping critical data in a private cloud',
          'Migrating all workloads to a single public cloud provider',
          'Isolating test environments from production',
        ],
        correctAnswerIndex: 1,
        feedback: 'Hybrid cloud is ideal for organizations that want to leverage public cloud benefits while retaining control over sensitive data in private environments.',
      },
      {
        id: 'cc-exam-q22',
        text: 'Which of the following cloud models provides the highest level of control over infrastructure?',
        options: ['SaaS', 'PaaS', 'IaaS', 'Serverless'],
        correctAnswerIndex: 2,
        feedback: 'IaaS gives users the most control over virtual machines, networks, and storage compared to higher-level services like PaaS or SaaS.',
      },
      {
        id: 'cc-exam-q23',
        text: 'Which of the following is a primary benefit of using the cloud for disaster recovery?',
        options: ['Higher latency', 'Reduced data redundancy', 'Rapid recovery and failover capabilities', 'Increased dependency on local hardware'],
        correctAnswerIndex: 2,
        feedback: 'Cloud-based disaster recovery offers fast recovery times, automated failover, and geographic redundancy.',
      },
      {
        id: 'cc-exam-q24',
        text: 'Which cloud computing model is best suited for organizations that want to run custom applications without managing the underlying infrastructure?',
        options: ['IaaS', 'PaaS', 'SaaS', 'Serverless'],
        correctAnswerIndex: 1,
        feedback: 'PaaS provides a development and deployment environment without requiring management of the underlying infrastructure.',
      },
      {
        id: 'cc-exam-q25',
        text: 'Which of the following best describes "scalability" in cloud computing?',
        options: [
          'Ability to increase or decrease resources based on demand',
          'Ability to encrypt data automatically',
          'Ability to store data in multiple formats',
          'Ability to host multiple applications on a single server',
        ],
        correctAnswerIndex: 0,
        feedback: 'Scalability allows cloud resources to expand or contract depending on workload requirements.',
      },
      {
        id: 'cc-exam-q26',
        text: 'Which of the following best describes "elasticity" in cloud computing?',
        options: [
          'Ability to change the price of cloud services dynamically',
          'Ability to add or remove resources automatically based on demand',
          'Ability to run applications offline',
          'Ability to deploy applications in multiple regions',
        ],
        correctAnswerIndex: 1,
        feedback: 'Elasticity refers to the automatic adjustment of resources in response to workload changes.',
      },
      {
        id: 'cc-exam-q27',
        text: 'Which of the following is a benefit of using cloud services for security?',
        options: [
          'Complete removal of threats',
          'Reduced visibility into security events',
          'Centralized security management and threat detection',
          'Increased complexity in managing firewalls',
        ],
        correctAnswerIndex: 2,
        feedback: 'Cloud providers offer advanced security tools and centralized dashboards to monitor and respond to threats effectively.',
      },
      {
        id: 'cc-exam-q28',
        text: 'Which of the following is a benefit of reliability in the cloud?',
        options: [
          'Lower costs due to reduced resource usage',
          'Consistent performance and uptime',
          'Greater flexibility in choosing hardware',
          'Faster deployment of new applications',
        ],
        correctAnswerIndex: 1,
        feedback: 'Reliability ensures that systems perform consistently and meet expected service levels.',
      },
      {
        id: 'cc-exam-q29',
        text: 'Which of the following best describes the "defense-in-depth" security strategy?',
        options: [
          'Using a single strong firewall to protect all assets',
          'Implementing multiple layers of security controls',
          'Relying solely on encryption for data protection',
          'Minimizing the number of security tools used',
        ],
        correctAnswerIndex: 1,
        feedback: 'Defense-in-depth involves layering multiple security measures (firewalls, encryption, IAM, etc.) to protect systems comprehensively.',
      },
      {
        id: 'cc-exam-q30',
        text: 'Which of the following is a benefit of using cloud services for governance?',
        options: [
          'Increased risk of unauthorized access',
          'Simplified compliance and policy enforcement',
          'Decreased visibility into resource usage',
          'Complex configuration of cloud environments',
        ],
        correctAnswerIndex: 1,
        feedback: 'Cloud platforms provide built-in governance tools like tagging, policies, and role-based access control (RBAC) to simplify compliance and management.',
      },
    ],
  },
  {
    id: 'azure-architecture-services-exam',
    name: 'Azure Architecture and Services Exam',
    description: 'Assess your knowledge of Azure\'s core architectural components, compute, networking, and storage services. Contains 30 questions. Target: 50 questions.',
    questions: [
      {
        id: 'aas-exam-q51',
        text: 'Which of the following best describes an Azure region?',
        options: [
          'A single data center located in a specific geographic area',
          'A group of data centers located in close proximity within a country',
          'A set of virtual machines grouped by availability',
          'A logical grouping of cloud services for billing purposes',
        ],
        correctAnswerIndex: 1,
        feedback: 'An Azure region is a set of data centers deployed within a latency-defined perimeter and connected through a dedicated regional low-latency network.',
      },
      {
        id: 'aas-exam-q52',
        text: 'What is the purpose of Azure region pairs?',
        options: [
          'To provide load balancing between regions',
          'To ensure compliance with local laws',
          'To offer geo-redundant backup and disaster recovery',
          'To allow customers to choose where their data resides',
        ],
        correctAnswerIndex: 2,
        feedback: 'Region pairs are used to provide high availability, disaster recovery, and replication across two regions within the same geography.',
      },
      {
        id: 'aas-exam-q53',
        text: 'Which Azure feature provides physical isolation of a customer’s resources from other tenants?',
        options: [
          'Availability zones',
          'Azure Dedicated Host',
          'Resource groups',
          'Management groups',
        ],
        correctAnswerIndex: 1,
        feedback: 'Azure Dedicated Host provides physical servers dedicated to one customer, offering host-level isolation for regulatory or compliance needs.',
      },
      {
        id: 'aas-exam-q54',
        text: 'What are Azure availability zones?',
        options: [
          'Logical partitions within a single data center',
          'Separate geographic locations within a region',
          'Zones that isolate applications based on industry regulations',
          'Physical locations within a region that have independent power and cooling',
        ],
        correctAnswerIndex: 3,
        feedback: 'Availability zones are physically separated locations within an Azure region, each with independent power, cooling, and networking.',
      },
      {
        id: 'aas-exam-q55',
        text: 'Which Azure component serves as the foundation for hosting virtual machines and other compute resources?',
        options: [
          'Azure App Service',
          'Azure Virtual Network',
          'Azure Storage Account',
          'Azure Datacenter',
        ],
        correctAnswerIndex: 3,
        feedback: 'Azure datacenters house the physical infrastructure, including servers, storage, and networking, used to run Azure services.',
      },
      {
        id: 'aas-exam-q56',
        text: 'Which of the following is a collection of related Azure resources grouped for management purposes?',
        options: [
          'Subscription',
          'Management group',
          'Resource group',
          'Availability set',
        ],
        correctAnswerIndex: 2,
        feedback: 'A resource group is a container that holds related resources for an Azure solution and allows them to be managed collectively.',
      },
      {
        id: 'aas-exam-q57',
        text: 'Which Azure concept defines the scope of access control and policies applied to resources?',
        options: [
          'Resource group',
          'Subscription',
          'Availability zone',
          'Virtual network',
        ],
        correctAnswerIndex: 1,
        feedback: 'Subscriptions are the primary billing and access control boundary in Azure. Policies and role-based access controls (RBAC) are often applied at this level.',
      },
      {
        id: 'aas-exam-q58',
        text: 'Which Azure feature allows you to organize multiple subscriptions into a hierarchy for governance?',
        options: [
          'Resource groups',
          'Management groups',
          'Policy definitions',
          'Azure Active Directory',
        ],
        correctAnswerIndex: 1,
        feedback: 'Management groups enable hierarchical organization of subscriptions to apply governance policies and access controls at scale.',
      },
      {
        id: 'aas-exam-q59',
        text: 'What is the correct order of the Azure resource hierarchy from top to bottom?',
        options: [
          'Resource Group → Subscription → Management Group',
          'Management Group → Subscription → Resource Group',
          'Subscription → Resource Group → Management Group',
          'Management Group → Resource Group → Subscription',
        ],
        correctAnswerIndex: 1,
        feedback: 'The Azure hierarchy is structured as: Management Groups → Subscriptions → Resource Groups → Resources.',
      },
      {
        id: 'aas-exam-q60',
        text: 'Which Azure service allows you to deploy and manage applications using containers?',
        options: [
          'Azure Kubernetes Service (AKS)',
          'Azure Functions',
          'Azure Logic Apps',
          'Azure DevOps Server',
        ],
        correctAnswerIndex: 0,
        feedback: 'Azure Kubernetes Service (AKS) provides a managed Kubernetes environment for deploying and managing containerized applications.',
      },
      {
        id: 'aas-exam-q61',
        text: 'Which Azure compute option is best suited for running custom code without provisioning or managing servers?',
        options: [
          'Azure Virtual Machines',
          'Azure Container Instances',
          'Azure Functions',
          'Azure Batch',
        ],
        correctAnswerIndex: 2,
        feedback: 'Azure Functions is a serverless compute service that runs code in response to events without requiring infrastructure management.',
      },
      {
        id: 'aas-exam-q62',
        text: 'Which Azure compute type should you use if you need full control over the operating system and application stack?',
        options: [
          'Azure Web Apps',
          'Azure Container Instances',
          'Azure Virtual Machines',
          'Azure Logic Apps',
        ],
        correctAnswerIndex: 2,
        feedback: 'Azure Virtual Machines give you full control over the OS, allowing customization, patching, and installation of any software.',
      },
      {
        id: 'aas-exam-q63',
        text: 'Which Azure compute service is best for scaling applications automatically based on demand?',
        options: [
          'Azure Virtual Machine Scale Sets',
          'Azure Container Registry',
          'Azure DevTest Labs',
          'Azure Site Recovery',
        ],
        correctAnswerIndex: 0,
        feedback: 'Virtual Machine Scale Sets allow automatic scaling of VM instances based on metrics like CPU usage or network traffic.',
      },
      {
        id: 'aas-exam-q64',
        text: 'Which Azure service enables remote desktop access to virtual machines?',
        options: [
          'Azure Bastion',
          'Azure Monitor',
          'Azure Security Center',
          'Azure Backup',
        ],
        correctAnswerIndex: 0,
        feedback: 'Azure Bastion provides secure and seamless RDP/SSH connectivity to virtual machines directly from the Azure portal.',
      },
      {
        id: 'aas-exam-q65',
        text: 'Which Azure networking component allows you to securely connect multiple virtual networks?',
        options: [
          'Azure Load Balancer',
          'Azure Application Gateway',
          'Virtual Network Peering',
          'Azure ExpressRoute',
        ],
        correctAnswerIndex: 2,
        feedback: 'Virtual Network Peering connects two virtual networks in the same region, enabling communication between resources as if they were on the same network.',
      },
      {
        id: 'aas-exam-q66',
        text: 'Which Azure service provides a private connection to Azure services without going over the public internet?',
        options: [
          'Azure DNS',
          'Azure Private Link',
          'Azure Front Door',
          'Azure Traffic Manager',
        ],
        correctAnswerIndex: 1,
        feedback: 'Azure Private Link allows you to access Azure PaaS services over a private endpoint, improving security and reducing exposure to the internet.',
      },
      {
        id: 'aas-exam-q67',
        text: 'Which Azure service enables hybrid connectivity between on-premises networks and Azure?',
        options: [
          'Azure Virtual Network',
          'Azure Firewall',
          'Azure ExpressRoute',
          'Azure Application Gateway',
        ],
        correctAnswerIndex: 2,
        feedback: 'Azure ExpressRoute provides private connectivity between on-premises infrastructure and Azure, bypassing the public internet.',
      },
      {
        id: 'aas-exam-q68',
        text: 'Which Azure storage service is designed for storing unstructured data such as text or binary data?',
        options: [
          'Azure Files',
          'Azure Table Storage',
          'Azure Blob Storage',
          'Azure Queue Storage',
        ],
        correctAnswerIndex: 2,
        feedback: 'Azure Blob Storage is optimized for storing massive amounts of unstructured data like text or binary files.',
      },
      {
        id: 'aas-exam-q69',
        text: 'Which Azure storage tier is best suited for frequently accessed data?',
        options: [
          'Archive Tier',
          'Cool Tier',
          'Hot Tier',
          'Cold Tier',
        ],
        correctAnswerIndex: 2,
        feedback: 'The Hot tier is optimized for frequently accessed data and offers the highest storage costs but lowest access costs.',
      },
      {
        id: 'aas-exam-q70',
        text: 'Which redundancy option replicates data across three copies within a single data center?',
        options: [
          'Locally Redundant Storage (LRS)',
          'Zone-Redundant Storage (ZRS)',
          'Geo-Redundant Storage (GRS)',
          'Read-Access Geo-Redundant Storage (RA-GRS)',
        ],
        correctAnswerIndex: 0,
        feedback: 'LRS stores three copies of your data within a single facility in one region, providing resilience against hardware failures.',
      },
      {
        id: 'aas-exam-q71',
        text: 'Which Azure storage redundancy option replicates data across two separate facilities within the same region?',
        options: [
          'Locally Redundant Storage (LRS)',
          'Zone-Redundant Storage (ZRS)',
          'Geo-Redundant Storage (GRS)',
          'Standard Redundancy',
        ],
        correctAnswerIndex: 1,
        feedback: 'ZRS replicates data synchronously across three storage clusters in different zones within the same region for high availability.',
      },
      {
        id: 'aas-exam-q72',
        text: 'Which tool would you use to copy large amounts of data to Azure Storage quickly and efficiently?',
        options: [
          'Azure CLI',
          'PowerShell',
          'AzCopy',
          'Azure Portal',
        ],
        correctAnswerIndex: 2,
        feedback: 'AzCopy is a command-line tool optimized for transferring large volumes of data to and from Azure Storage.',
      },
      {
        id: 'aas-exam-q73',
        text: 'Which Azure service helps assess and migrate on-premises workloads to Azure?',
        options: [
          'Azure Backup',
          'Azure Migrate',
          'Azure Site Recovery',
          'Azure Cost Management',
        ],
        correctAnswerIndex: 1,
        feedback: 'Azure Migrate provides tools to assess and migrate servers, databases, and applications from on-premises to Azure.',
      },
      {
        id: 'aas-exam-q74',
        text: 'Which Azure service is designed for moving large amounts of data offline to Azure?',
        options: [
          'Azure Import/Export',
          'Azure Data Box',
          'Azure Migrate',
          'Azure File Sync',
        ],
        correctAnswerIndex: 1,
        feedback: 'Azure Data Box is a physical device used to transfer terabytes of data to Azure when network bandwidth is limited.',
      },
      {
        id: 'aas-exam-q75',
        text: 'Which Azure identity service is used to manage users and groups for cloud-based applications?',
        options: [
          'Microsoft Entra ID',
          'Azure AD Domain Services',
          'Azure Information Protection',
          'Azure Key Vault',
        ],
        correctAnswerIndex: 0,
        feedback: 'Microsoft Entra ID (formerly Azure Active Directory) is a cloud-based identity and access management service.',
      },
      {
        id: 'aas-exam-q76',
        text: 'Which authentication method allows users to sign in once and access multiple applications without re-entering credentials?',
        options: [
          'Multi-Factor Authentication (MFA)',
          'Passwordless Authentication',
          'Single Sign-On (SSO)',
          'Biometric Authentication',
        ],
        correctAnswerIndex: 2,
        feedback: 'SSO allows users to authenticate once and gain access to multiple systems without additional logins.',
      },
      {
        id: 'aas-exam-q77',
        text: 'Which Azure service supports external collaboration with business partners or customers?',
        options: [
          'Microsoft Entra ID',
          'Microsoft Entra External ID',
          'Microsoft Entra Domain Services',
          'Microsoft Defender for Identity',
        ],
        correctAnswerIndex: 1,
        feedback: 'Microsoft Entra External ID (formerly B2B and B2C) enables secure collaboration with external users outside your organization.',
      },
      {
        id: 'aas-exam-q78',
        text: 'Which Azure feature enforces conditional access policies based on user, device, or location?',
        options: [
          'Azure RBAC',
          'Microsoft Entra Conditional Access',
          'Azure Security Center',
          'Azure Policy',
        ],
        correctAnswerIndex: 1,
        feedback: 'Microsoft Entra Conditional Access allows administrators to enforce policies that grant or deny access based on specific conditions.',
      },
      {
        id: 'aas-exam-q79',
        text: 'Which Azure service enables fine-grained access management to resources using roles?',
        options: [
          'Azure Security Center',
          'Azure Monitor',
          'Azure Role-Based Access Control (RBAC)',
          'Microsoft Entra ID',
        ],
        correctAnswerIndex: 2,
        feedback: 'Azure RBAC allows assigning roles to users, groups, or applications to control what they can do with Azure resources.',
      },
      {
        id: 'aas-exam-q80',
        text: 'Which security model assumes no implicit trust and requires verification for every access request?',
        options: [
          'Defense-in-depth',
          'Zero Trust',
          'Shared Responsibility Model',
          'Least Privilege',
        ],
        correctAnswerIndex: 1,
        feedback: 'Zero Trust is a security framework that assumes breaches are inevitable and requires continuous verification of all access requests.',
      },
      // ... more questions to reach 50 if needed
    ],
  },
  {
    id: 'azure-identity-access-security-exam',
    name: 'Azure Identity, Access, and Security Exam',
    description: 'Challenge your knowledge on directory services, authentication, external identities, access control, and security models in Azure. Contains 20 questions. Target: 50 questions.',
    questions: [
      {
        id: 'aias-exam-q81',
        text: 'Which of the following is a key factor that affects costs in Azure?',
        options: [
          'The number of users accessing Azure',
          'The geographic location of the resource',
          'The type of authentication used',
          'The version of Microsoft Entra ID',
        ],
        correctAnswerIndex: 1,
        feedback: 'Geographic location impacts cost because some regions have higher operational expenses, affecting pricing for resources like storage and compute.',
      },
      {
        id: 'aias-exam-q82',
        text: 'Which tool would you use to estimate the monthly cost of running your workloads in Azure?',
        options: [
          'Azure Advisor',
          'Azure Pricing Calculator',
          'Azure Cost Management + Billing',
          'Azure Total Cost of Ownership (TCO) Calculator',
        ],
        correctAnswerIndex: 1,
        feedback: 'The Azure Pricing Calculator allows you to estimate monthly costs based on the services you plan to use.',
      },
      {
        id: 'aias-exam-q83',
        text: 'Which Azure feature helps track and manage cloud spending across subscriptions and resource groups?',
        options: [
          'Azure Monitor',
          'Azure Cost Management',
          'Azure Security Center',
          'Azure Policy',
        ],
        correctAnswerIndex: 1,
        feedback: 'Azure Cost Management provides tools to monitor, analyze, and optimize cloud spending across your Azure environment.',
      },
      {
        id: 'aias-exam-q84',
        text: 'What is the purpose of tags in Azure?',
        options: [
          'To secure virtual machines from unauthorized access',
          'To organize resources for billing or management',
          'To define access control policies',
          'To automate deployment of resources',
        ],
        correctAnswerIndex: 1,
        feedback: 'Tags are metadata labels applied to resources to help organize them logically for management, filtering, and cost tracking.',
      },
      {
        id: 'aias-exam-q85',
        text: 'Which of the following is a benefit of using Azure Policy?',
        options: [
          'Automate backups of virtual machines',
          'Enforce governance rules such as naming conventions or approved VM sizes',
          'Monitor application performance',
          'Secure network traffic between virtual machines',
        ],
        correctAnswerIndex: 1,
        feedback: 'Azure Policy enables you to create and enforce organizational standards and compliance rules across your Azure environment.',
      },
      {
        id: 'aias-exam-q86',
        text: 'Which Azure service helps ensure regulatory compliance and visibility into data governance?',
        options: [
          'Azure Key Vault',
          'Microsoft Purview',
          'Azure Sentinel',
          'Azure Monitor',
        ],
        correctAnswerIndex: 1,
        feedback: 'Microsoft Purview provides a unified data governance solution for discovering, classifying, and managing data across hybrid environments.',
      },
      {
        id: 'aias-exam-q87',
        text: 'Which Azure feature prevents accidental deletion or modification of critical resources?',
        options: [
          'Azure Policy',
          'Resource Locks',
          'Role-Based Access Control (RBAC)',
          'Azure Security Center',
        ],
        correctAnswerIndex: 1,
        feedback: 'Resource locks help protect important resources from accidental changes or deletions by locking them at the resource group or individual resource level.',
      },
      {
        id: 'aias-exam-q88',
        text: 'Which Azure portal feature allows you to customize dashboards and monitor your most important resources?',
        options: [
          'Azure Monitor',
          'Azure Dashboard',
          'Azure CLI',
          'Azure PowerShell',
        ],
        correctAnswerIndex: 1,
        feedback: 'Azure Dashboards allow users to create personalized views of their key resources and metrics for easy monitoring.',
      },
      {
        id: 'aias-exam-q89',
        text: 'Which Azure tool provides command-line access for managing resources and can be used in scripts or automation?',
        options: [
          'Azure Cloud Shell',
          'Azure DevOps',
          'Azure Monitor',
          'Azure Logic Apps',
        ],
        correctAnswerIndex: 0,
        feedback: 'Azure Cloud Shell offers a browser-based shell experience with both Azure CLI and PowerShell for managing Azure resources.',
      },
      {
        id: 'aias-exam-q90',
        text: 'Which Azure service enables management of on-premises and multi-cloud servers as if they were in Azure?',
        options: [
          'Azure Arc',
          'Azure Migrate',
          'Azure Site Recovery',
          'Azure Backup',
        ],
        correctAnswerIndex: 0,
        feedback: 'Azure Arc extends Azure management capabilities to on-premises and multi-cloud environments, enabling centralized governance and deployment.',
      },
      {
        id: 'aias-exam-q91',
        text: 'Which term describes the practice of defining infrastructure through code, allowing automated provisioning and consistent deployments?',
        options: [
          'Infrastructure as a Service (IaaS)',
          'Platform as a Service (PaaS)',
          'Infrastructure as Code (IaC)',
          'Software as a Service (SaaS)',
        ],
        correctAnswerIndex: 2,
        feedback: 'Infrastructure as Code (IaC) uses configuration files to manage and provision infrastructure in a repeatable and automated way.',
      },
      {
        id: 'aias-exam-q92',
        text: 'Which Azure service allows you to deploy and manage resources using JSON templates?',
        options: [
          'Azure DevOps',
          'Azure Resource Manager (ARM)',
          'Azure CLI',
          'Azure Functions',
        ],
        correctAnswerIndex: 1,
        feedback: 'Azure Resource Manager (ARM) supports deploying resources using declarative JSON templates, ensuring consistent and repeatable deployments.',
      },
      {
        id: 'aias-exam-q93',
        text: 'Which Azure service provides recommendations to improve performance, security, and cost efficiency?',
        options: [
          'Azure Advisor',
          'Azure Monitor',
          'Azure Security Center',
          'Azure Policy',
        ],
        correctAnswerIndex: 0,
        feedback: 'Azure Advisor analyzes your Azure resources and provides personalized recommendations to optimize cost, performance, availability, and security.',
      },
      {
        id: 'aias-exam-q94',
        text: 'Which Azure service monitors the health of Azure services and alerts you about issues affecting your resources?',
        options: [
          'Azure Advisor',
          'Azure Service Health',
          'Azure Monitor',
          'Azure Security Center',
        ],
        correctAnswerIndex: 1,
        feedback: 'Azure Service Health keeps you informed about the health status of Azure services and how outages may affect your resources.',
      },
      {
        id: 'aias-exam-q95',
        text: 'Which Azure service collects and analyzes telemetry data from cloud and on-premises environments?',
        options: [
          'Azure Log Analytics',
          'Azure Advisor',
          'Azure Automation',
          'Azure Policy',
        ],
        correctAnswerIndex: 0,
        feedback: 'Log Analytics, part of Azure Monitor, collects log data from various sources and allows querying and analysis for troubleshooting and monitoring.',
      },
      {
        id: 'aias-exam-q96',
        text: 'Which Azure service allows you to set up alerts based on specific metrics or logs?',
        options: [
          'Azure Monitor Alerts',
          'Azure Advisor',
          'Azure Security Center',
          'Azure Policy',
        ],
        correctAnswerIndex: 0,
        feedback: 'Azure Monitor Alerts notify you when certain conditions are met, such as high CPU usage or failed login attempts.',
      },
      {
        id: 'aias-exam-q97',
        text: 'Which Azure service helps identify performance bottlenecks and exceptions in web applications?',
        options: [
          'Application Insights',
          'Azure Monitor',
          'Azure Security Center',
          'Azure Advisor',
        ],
        correctAnswerIndex: 0,
        feedback: 'Application Insights is an analytics service that monitors web applications and identifies performance issues and exceptions.',
      },
      {
        id: 'aias-exam-q98',
        text: 'Which Azure service provides proactive cloud security and threat protection?',
        options: [
          'Azure Security Center',
          'Microsoft Defender for Cloud',
          'Azure Monitor',
          'Microsoft Entra ID',
        ],
        correctAnswerIndex: 1,
        feedback: 'Microsoft Defender for Cloud (formerly Azure Security Center) provides unified security management and advanced threat protection across hybrid cloud workloads.',
      },
      {
        id: 'aias-exam-q99',
        text: 'Which Azure service automates the enforcement of security best practices and compliance?',
        options: [
          'Azure Security Center', // Note: Could also be Microsoft Defender for Cloud, but Security Center is often the broader term in contexts like this.
          'Azure Policy',
          'Microsoft Defender for Cloud',
          'Azure Monitor',
        ],
        correctAnswerIndex: 2, // Changed to C as Microsoft Defender for Cloud is more precise here.
        feedback: 'Microsoft Defender for Cloud integrates with Azure Security features to assess and enforce security best practices across your cloud environment.',
      },
      {
        id: 'aias-exam-q100',
        text: 'Which Azure service helps meet compliance requirements by offering built-in policy definitions?',
        options: [
          'Azure Monitor',
          'Azure Advisor',
          'Azure Policy',
          'Azure CLI',
        ],
        correctAnswerIndex: 2,
        feedback: 'Azure Policy includes built-in compliance policy definitions that help organizations meet regulatory requirements like ISO, GDPR, and HIPAA.',
      },
      // ... more questions to reach 50 if needed
    ],
  },
  {
    id: 'azure-management-governance-exam',
    name: 'Azure Management and Governance Exam',
    description: 'Test your skills in cost management, governance tools (Policy, Purview), resource deployment, and monitoring in Azure. Target: 50 questions.',
    questions: [
       {
        id: 'amg-exam-q1',
        text: 'Placeholder question for Azure Management and Governance 1?',
        options: ['Option A', 'Option B', 'Option C', 'Option D'],
        correctAnswerIndex: 0,
        feedback: 'This is a placeholder explanation for AMG question 1.',
      },
      {
        id: 'amg-exam-q2',
        text: 'Placeholder question for Azure Management and Governance 2?',
        options: ['Option A', 'Option B', 'Option C', 'Option D'],
        correctAnswerIndex: 1,
        feedback: 'This is a placeholder explanation for AMG question 2.',
      },
      {
        id: 'amg-exam-q3',
        text: 'Placeholder question for Azure Management and Governance 3?',
        options: ['Option A', 'Option B', 'Option C', 'Option D'],
        correctAnswerIndex: 2,
        feedback: 'This is a placeholder explanation for AMG question 3.',
      },
      {
        id: 'amg-exam-q4',
        text: 'Placeholder question for Azure Management and Governance 4?',
        options: ['Option A', 'Option B', 'Option C', 'Option D'],
        correctAnswerIndex: 3,
        feedback: 'This is a placeholder explanation for AMG question 4.',
      },
      {
        id: 'amg-exam-q5',
        text: 'Placeholder question for Azure Management and Governance 5?',
        options: ['Option A', 'Option B', 'Option C', 'Option D'],
        correctAnswerIndex: 0,
        feedback: 'This is a placeholder explanation for AMG question 5.',
      },
      {
        id: 'amg-exam-q6',
        text: 'Placeholder question for Azure Management and Governance 6?',
        options: ['Option A', 'Option B', 'Option C', 'Option D'],
        correctAnswerIndex: 1,
        feedback: 'This is a placeholder explanation for AMG question 6.',
      },
      {
        id: 'amg-exam-q7',
        text: 'Placeholder question for Azure Management and Governance 7?',
        options: ['Option A', 'Option B', 'Option C', 'Option D'],
        correctAnswerIndex: 2,
        feedback: 'This is a placeholder explanation for AMG question 7.',
      },
      {
        id: 'amg-exam-q8',
        text: 'Placeholder question for Azure Management and Governance 8?',
        options: ['Option A', 'Option B', 'Option C', 'Option D'],
        correctAnswerIndex: 3,
        feedback: 'This is a placeholder explanation for AMG question 8.',
      },
      {
        id: 'amg-exam-q9',
        text: 'Placeholder question for Azure Management and Governance 9?',
        options: ['Option A', 'Option B', 'Option C', 'Option D'],
        correctAnswerIndex: 0,
        feedback: 'This is a placeholder explanation for AMG question 9.',
      },
      {
        id: 'amg-exam-q10',
        text: 'Placeholder question for Azure Management and Governance 10?',
        options: ['Option A', 'Option B', 'Option C', 'Option D'],
        correctAnswerIndex: 1,
        feedback: 'This is a placeholder explanation for AMG question 10.',
      },
      // ... more questions to reach 50
    ],
  },
];

export const getExamById = (id: string): Exam | undefined => {
  return exams.find((exam) => exam.id === id);
};

    